name: Create release package

on:
  workflow_dispatch:
  push:
    branches:
      - "release/*"

env:
  SERVER: production
  PUBLIC_PATH: /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Extract release name from branch ref
        shell: bash
        run: echo "{branch}={$(echo ${GITHUB_REF#refs/heads/release/})}" >> $GITHUB_OUTPUT
        id: release_name

      - name: Create release bundle
        run: git archive HEAD --prefix="bstk_datatables-${{ github.sha }}/" --output="bstk_datatables-${{ github.sha }}.tgz"

      - name: Create release
        uses: "softprops/action-gh-release@v3.0.0"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "${{ steps.release_name.outputs.branch }}"
          draft: true
          prerelease: false
          title: "Release / ${{ steps.release_name.outputs.branch }}"
          files: |
            bstk_datatables-${{ github.sha }}.tgz
