name: Publish Test Results

on:
  workflow_run:
    workflows: ["Check & Test"]
    types:
      - completed

jobs:
  publish-test-results:
    name: "Publish Test Results"
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: hashFiles('artifacts/**/*.xml') != ''
        with:
          github_token: "${{github.token}}"
          files: artifacts/**/*.xml
          test_changes_limit: 0
          report_individual_runs: true
          check_run_annotations: all tests, skipped tests
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: "${{github.token}}"
          ref: ${{ github.event.workflow_run.head_sha }}
          path: "onespark"

      - name: Run Test Report
        uses: dorny/test-reporter@v1
        if: hashFiles('artifacts/**/*.xml') != ''
        with:
          list-suites: "all"
          list-tests: "all"
          fail-on-error: true
          max-annotations: "10"
          artifact: /Test Results (.*)/
          path: "*-test-results.xml"
          name: "Test Report $1"
          reporter: java-junit
          working-directory: "onespark"
