name: Check & Test

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "poetry.lock"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - python-version: "3.8"
            lint: false
          - python-version: "3.9"
            lint: true
          - python-version: "3.10"
            lint: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.build-config.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.build-config.python-version }}

      - uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}-${{ matrix.build-config.python-version }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry install --no-interaction

      - name: Lint with black
        if: matrix.build-config.lint
        run: |
          poetry run black --check --diff bstk_datatables

      - name: Run pyflakes (flake8)
        if: matrix.build-config.lint
        run: |
          poetry run flake8 bstk_datatables

      - name: Execute Unit Tests
        run: |
          poetry run pytest --junit-xml=${{ matrix.build-config.python-version }}-unit-test-results.xml tests/unit
        continue-on-error: true

      - name: Execute Integration Tests
        run: |
          poetry run pytest --junit-xml=${{ matrix.build-config.python-version }}-integration-test-results.xml tests/integration
        continue-on-error: true

      - name: Execute Functional Tests
        run: |
          poetry run pytest --junit-xml=${{ matrix.build-config.python-version }}-functional-test-results.xml tests/functional
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (Python ${{ matrix.build-config.python-version }})
          path: "*-test-results.xml"

      - name: Upload Test Logs
        uses: actions/upload-artifact@v3
        with:
          name: Test Logs (Python ${{ matrix.build-config.python-version }})
          path: "logs/*.log"
          retention-days: 1

  publish-event-file:
    name: "Event File"
    needs: build-and-test
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Upload Event File
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
